#!/usr/bin/env bash
#
# Deploys the karaokio party-box stacks, in dependency order, from
# cloudformation-toolkit templates. Idempotent: `aws cloudformation deploy`
# no-ops on an unchanged stack.
#
# Required env:
#   TOOLKIT_DIR   checkout of patrickisgreat/cloudformation-toolkit
#   AWS_REGION    e.g. us-east-1
# Optional env:
#   ALLOWED_CIDR  ingress CIDR for the app port (default 0.0.0.0/0 — the app
#                 enforces party-code auth; narrow for defense in depth)
#
# The service stack deploys twice on the very first run: the EFS file system
# needs the task security group (created by the service stack), and the service
# needs the EFS ids. Every later run resolves the EFS ids up front and deploys
# the service exactly once.

set -euo pipefail

: "${TOOLKIT_DIR:?set TOOLKIT_DIR to a cloudformation-toolkit checkout}"
: "${AWS_REGION:?set AWS_REGION}"

PREFIX=karaokio
ENVIRONMENT=prod
TEMPLATES="$TOOLKIT_DIR/templates"
ALLOWED_CIDR="${ALLOWED_CIDR:-0.0.0.0/0}"

deploy() {
  local stack="$1" template="$2"; shift 2
  echo "──▶ ${stack}"
  aws cloudformation deploy \
    --region "$AWS_REGION" \
    --stack-name "$stack" \
    --template-file "$template" \
    --no-fail-on-empty-changeset \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameter-overrides "$@"
}

output() {
  aws cloudformation describe-stacks --region "$AWS_REGION" \
    --stack-name "$1" \
    --query "Stacks[0].Outputs[?OutputKey=='$2'].OutputValue" --output text
}

stack_exists() {
  aws cloudformation describe-stacks --region "$AWS_REGION" \
    --stack-name "$1" >/dev/null 2>&1
}

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

# 0. The deploy role's own stack. Created once by infra/bootstrap.sh with
#    human credentials (CI can't create the credential CI runs as); from then
#    on every Infra run re-deploys it, so its definition lives here and drift
#    self-heals. The role can update its own stack: it holds IAMFullAccess.
deploy "$PREFIX-github-oidc" "$TEMPLATES/foundation/github-oidc-role/template.yaml" \
  "NamePrefix=$PREFIX" \
  "GitHubOrg=patrickisgreat" "GitHubRepo=karaokio" \
  "ManagedPolicyArn=arn:aws:iam::aws:policy/PowerUserAccess" \
  "ManagedPolicyArn2=arn:aws:iam::aws:policy/IAMFullAccess"

# 1. Network — public subnets only, no NAT (tasks get public IPs instead)
deploy "$PREFIX-vpc" "$TEMPLATES/foundation/vpc/template.yaml" \
  "NamePrefix=$PREFIX" "Environment=$ENVIRONMENT" \
  "NatGatewayMode=none" "AvailabilityZoneCount=2"

VPC_ID=$(output "$PREFIX-vpc" VpcId)
PUBLIC_SUBNETS=$(output "$PREFIX-vpc" PublicSubnetIds)
SUBNET_1=${PUBLIC_SUBNETS%%,*}
SUBNET_2=${PUBLIC_SUBNETS##*,}

# 2. Registry
deploy "$PREFIX-ecr" "$TEMPLATES/containers/ecr-repository/template.yaml" \
  "NamePrefix=$PREFIX" "RepositorySuffix=app"

IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PREFIX/app"

# 3. Cluster — pure Fargate Spot: ~70% cheaper, and a 2-minute reclamation
#    warning is an acceptable party risk. Container Insights off (it bills
#    per metric and CloudWatch logs already cover a single-service box).
deploy "$PREFIX-cluster" "$TEMPLATES/containers/ecs-cluster/template.yaml" \
  "NamePrefix=$PREFIX" "Environment=$ENVIRONMENT" \
  "SpotWeight=1" "OnDemandWeight=0" "OnDemandBaseCount=0" \
  "ContainerInsights=disabled"

CLUSTER_NAME=$(output "$PREFIX-cluster" ClusterName)

# 3b. Party auth secrets — generated by Secrets Manager, never in a template,
#     a parameter, or CI logs. The host reads the PIN once:
#     aws secretsmanager get-secret-value --secret-id prod/karaokio/host-pin \
#       --query SecretString --output text
deploy "$PREFIX-secret-hostpin" "$TEMPLATES/foundation/secret/template.yaml" \
  "NamePrefix=$PREFIX" "Environment=$ENVIRONMENT" "SecretSuffix=host-pin" \
  "SecretDescription=Karaokio host PIN - unlocks host controls in the app" \
  "SecretStringTemplate=" "PasswordLength=8"

deploy "$PREFIX-secret-session" "$TEMPLATES/foundation/secret/template.yaml" \
  "NamePrefix=$PREFIX" "Environment=$ENVIRONMENT" "SecretSuffix=session-secret" \
  "SecretDescription=Karaokio session-signing secret - rotating it logs everyone out" \
  "SecretStringTemplate=" "PasswordLength=48"

HOSTPIN_ARN=$(output "$PREFIX-secret-hostpin" SecretArn)
SESSION_ARN=$(output "$PREFIX-secret-session" SecretArn)

# 4. Service. EFS params only when the EFS stack already exists (see header).
SERVICE_PARAMS=(
  "NamePrefix=$PREFIX" "Environment=$ENVIRONMENT" "ServiceSuffix=app"
  "ClusterName=$CLUSTER_NAME" "VpcId=$VPC_ID" "SubnetIds=$PUBLIC_SUBNETS"
  "AssignPublicIp=ENABLED" "UseClusterCapacityProviderStrategy=true"
  "ImageUri=$IMAGE_URI:bootstrap" "ContainerPort=3000"
  "Cpu=4096" "Memory=8192"
  "DesiredCount=0" "MinCapacity=0" "MaxCapacity=1"
  "EnvVar1Name=DATA_ROOT" "EnvVar1Value=/data"
  "EnvVar2Name=ENABLE_TORRENT_DOWNLOAD" "EnvVar2Value=false"
  "Secret1Name=HOST_PIN" "Secret1Arn=$HOSTPIN_ARN"
  "Secret2Name=PARTY_SESSION_SECRET" "Secret2Arn=$SESSION_ARN"
)

EFS_READY=false
if stack_exists "$PREFIX-efs"; then
  EFS_READY=true
  SERVICE_PARAMS+=(
    "EfsFileSystemId=$(output "$PREFIX-efs" FileSystemId)"
    "EfsAccessPointId=$(output "$PREFIX-efs" AccessPointId)"
    "EfsMountPath=/data"
  )
fi

deploy "$PREFIX-service" "$TEMPLATES/containers/fargate-service/template.yaml" \
  "${SERVICE_PARAMS[@]}"

TASK_SG=$(output "$PREFIX-service" TaskSecurityGroupId)

# 5. Public ingress to the app port (karaokio-owned template)
deploy "$PREFIX-ingress" "$(dirname "$0")/templates/party-ingress.yaml" \
  "TaskSecurityGroupId=$TASK_SG" "AllowedCidr=$ALLOWED_CIDR" "Port=3000"

# 6. Persistent storage, NFS scoped to the task security group
deploy "$PREFIX-efs" "$TEMPLATES/data/efs-filesystem/template.yaml" \
  "NamePrefix=$PREFIX" "Environment=$ENVIRONMENT" \
  "VpcId=$VPC_ID" "SubnetId1=$SUBNET_1" "SubnetId2=$SUBNET_2" \
  "ClientSecurityGroupId=$TASK_SG"

# 7. First run only: re-deploy the service now that the EFS ids exist
if [ "$EFS_READY" = false ]; then
  SERVICE_PARAMS+=(
    "EfsFileSystemId=$(output "$PREFIX-efs" FileSystemId)"
    "EfsAccessPointId=$(output "$PREFIX-efs" AccessPointId)"
    "EfsMountPath=/data"
  )
  deploy "$PREFIX-service" "$TEMPLATES/containers/fargate-service/template.yaml" \
    "${SERVICE_PARAMS[@]}"
fi

echo ""
echo "✅ Party box infrastructure deployed."
echo "   cluster:  $CLUSTER_NAME"
echo "   service:  $PREFIX-app"
echo "   registry: $IMAGE_URI"
