#!/bin/bash

# Test setup script for Karaokio
# Installs required dependencies and sets up test environment

set -e

echo "🧪 Setting up Karaokio test environment..."

# Check if we're on macOS or Linux
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    echo "📦 Installing macOS dependencies..."
    
    if ! command -v brew &> /dev/null; then
        echo "❌ Homebrew not found. Please install Homebrew first."
        exit 1
    fi
    
    brew install ffmpeg python3 node
    
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    echo "📦 Installing Linux dependencies..."
    
    sudo apt-get update
    sudo apt-get install -y ffmpeg python3 python3-pip nodejs npm
    
else
    echo "❌ Unsupported operating system: $OSTYPE"
    exit 1
fi

# Install Python packages
echo "🐍 Installing Python packages..."
pip3 install demucs spleeter youtube-dl

# Install Node.js dependencies
echo "📦 Installing Node.js dependencies..."
npm install

# Create test directories
echo "📁 Creating test directories..."
mkdir -p tests/temp
mkdir -p tests/fixtures
mkdir -p coverage

# Set up test environment file
echo "⚙️ Setting up test environment..."
cat > .env.test << EOF
NODE_ENV=test
UPLOAD_DIR=./tests/temp/uploads
OUTPUT_DIR=./tests/temp/output
TEMP_DIR=./tests/temp/processing
CACHE_DIR=./tests/temp/cache
DOWNLOAD_DIR=./tests/temp/downloads
YOUTUBE_VIDEO_DIR=./tests/temp/youtube

# Disable external services in tests
ENABLE_TORRENT_DOWNLOAD=false
ENABLE_YOUTUBE_DOWNLOAD=false

# Test database
TEST_DB_PATH=./tests/temp/test-karaoke.db

# Quick timeouts for tests
TORRENT_TIMEOUT=5000
YOUTUBE_TIMEOUT=5000
MAX_PROCESSING_TIME=30000
EOF

# Create sample test files
echo "📄 Creating test fixtures..."
mkdir -p tests/fixtures

# Create a small audio file for testing (silence)
if command -v ffmpeg &> /dev/null; then
    ffmpeg -f lavfi -i anullsrc=r=44100:cl=mono -t 5 -c:a pcm_s16le tests/fixtures/test-audio.wav -y 2>/dev/null
    ffmpeg -f lavfi -i testsrc=duration=5:size=320x240:rate=1 tests/fixtures/test-video.mp4 -y 2>/dev/null
    echo "✅ Created test audio and video fixtures"
fi

# Create test lyrics file
cat > tests/fixtures/test-lyrics.lrc << EOF
[00:00.50]This is a test lyric
[00:03.00]For testing purposes only
[00:05.50]Generated by the test setup
EOF

echo "✅ Test environment setup complete!"
echo ""
echo "🚀 You can now run tests:"
echo "  npm test                  # Run all tests"
echo "  npm run test:watch        # Run tests in watch mode"
echo "  npm run test:coverage     # Run tests with coverage"
echo ""
echo "🧹 To clean up test files:"
echo "  npm run test:clean        # Remove test artifacts"